### ISSUE TITLE
You need a licence for re-use of your logos

### ISSUE THREAD

**Issue by marioa** [rseng/logos#1]

**Comment by vsoch** [comment]
Why do you want to reuse them?

**Comment by marioa** [comment]
I suspect what I mean is if derived works are allowed - I was creating a regional RSE group so customised. See: https://github.com/ScotRSE - if this is not allowed then I will take off. Strictly speaking, as there is no licence this is not allowed. Happy to take off.

**Comment by vsoch** [comment]
Oh I see! I can definitely add a license later today. I would also maybe remove the clear backing with the white lines? It was there to signify the US.

**Comment by vsoch** [comment]
Maybe you could remove the horizontal white lines and put a white lines X to match your flag, then you wouldn’t need to explicitly put it there behind the logo?

**Comment by marioa** [comment]
Actually, I am not that bothered about the white lines, I see what you mean though. I think I grabbed the rse logo from here https://us-rse.org/rse-stories/ which I think is also you before I found your logo repo. I found the US repo. I made the same suggestion about licensing to https://github.com/usrse/logo :-) .

**Comment by vsoch** [comment]
Haha yes that is me as well! I created this derivation (and the RSE Stories one) because I really didn't like our original US-RSE logo - it was rather ugly in fact. We have a new one now so that's no longer a problem, haha.

Anyway - just added a LICENSE - re-use away!

https://github.com/rseng/logos/blob/master/LICENSE

**Comment by marioa** [comment]
Thank you.
